name: robot-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cmake
  - pkg-config
  - make
  - ninja
  - eigen
  - pinocchio
  - eigenpy
  - hpp-fcl
  - assimp
  - fmt
  - pybind11 
  - boost
  - numpy=1.26
  - pip
  - pip:
      - doxystub
      - mujoco